input.onButtonPressed(Button.A, function () {
    music.setVolume(100)
    music.playMelody("G A B - G A B - ", 140)
    music.playMelody("- G A B C5 B - - ", 155)
    music.playMelody("G B G F E - - - ", 140)
    music.playMelody("- F E - D E - - ", 120)
    music.playMelody("G A B - G A B - ", 140)
    music.playMelody("- - G A B C5 B - ", 160)
    music.playMelody("- G A B A G - - ", 140)
    music.playMelody("- G E D G - - - ", 180)
    music.playMelody("D E F - E F G - ", 200)
    music.playMelody("- - B G A - - - ", 222)
    music.playMelody("D E F - E F G - ", 200)
    music.playMelody("- - - F G A - - ", 260)
    music.playMelody("D E F - E F G - ", 200)
    music.playMelody("- - B G A - - - ", 222)
    music.playMelody("- E E E D D - - ", 400)
    music.playMelody("- F F F E E - - ", 400)
    music.playMelody("- G G G F F - - ", 400)
    music.playMelody("G G F F D G G G ", 400)
})
